apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app.kubernetes.io/name: blog
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blog
      app.kubernetes.io/component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: blog
        image: nullchannel/blog:0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 1313
