apiVersion: v1
kind: Service
metadata:
  name: echo-frontend
  labels:
    app.kubernetes.io/name: echo
    app.kubernetes.io/component: echo-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: echo
    app.kubernetes.io/component: echo-frontend
