apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-frontend
  labels:
    app.kubernetes.io/name: echo
    app.kubernetes.io/component: echo-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
      app.kubernetes.io/component: echo-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
        app.kubernetes.io/component: echo-frontend
    spec:
      containers:
      - name: echo
        #image: paulczar/gb-frontend:v5
        image: jmalloc/echo-server
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
